// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgClQZCRdY00uMvScaUsKwG1OOsBSd2PI',
    appId: '1:712343536258:web:fc4e32b41164dc764baa9b',
    messagingSenderId: '712343536258',
    projectId: 'mynotes-5ba89',
    authDomain: 'mynotes-5ba89.firebaseapp.com',
    storageBucket: 'mynotes-5ba89.appspot.com',
    measurementId: 'G-2290BMT3LT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqhyIuX5CVccGyQYrMfqOceKsNWrvis6g',
    appId: '1:712343536258:android:e5ff0da3771a48c84baa9b',
    messagingSenderId: '712343536258',
    projectId: 'mynotes-5ba89',
    storageBucket: 'mynotes-5ba89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYWMCfo6D9J7PVL1h0qjG56asyhRYZCAQ',
    appId: '1:712343536258:ios:339541134c72bfc84baa9b',
    messagingSenderId: '712343536258',
    projectId: 'mynotes-5ba89',
    storageBucket: 'mynotes-5ba89.appspot.com',
    iosClientId: '712343536258-plbrqqvrig4nkel9uq1t1pgo4dfjupkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
